### ISSUE TITLE
font error

### ISSUE THREAD

**Issue by komarnickolas** [Jypotheren734x/board-game-sharing#58]
![image](https://cloud.githubusercontent.com/assets/8580362/8949264/c25c1fe0-3565-11e5-951f-dba60c63ebd6.png)
 fix this

**Comment by theCyanGiant** [comment]
could this be fixed by changing from http://fonts.google.....
to                                                       https://fonts.google....
I'm not sure that google has it on a secure server, and I only throw the issue when I am on a heroku live page, so I can't debug from a local file.

**Comment by theCyanGiant** [comment]
Fixed with above idea

**Comment by nicedive4u** [comment]
Hi,

Could anybody tell me in which file is this error located?
I have the same problem, but couldn't find out in which file I have to look.
Please help: www.nicedive4u.de
Using Joomla, Gantry 4 and a theme from Themeshunt.

Thanks a lot
Thomas
