### ISSUE TITLE
Forums comunication

### ISSUE THREAD

**Issue by theCyanGiant** [Jypotheren734x/board-game-sharing#63]
![image](https://cloud.githubusercontent.com/assets/12467136/8962267/8d9377ea-35ce-11e5-9db7-e15b615a00b1.png)
Lets change the Username column to the something that makes it clear that is who we are trying to tag. Ideas for that title? maybe the same Recipient as we are using in the prompt box?
Also we should implement a column for requesting user.

**Comment by wmwilliams** [comment]
I changed the name of the first column and added a third column. As far as auto populating the third column when somoene is signed in....I dont know. I could definitely add an input box though and have someone be able to type who the message is from. I guess well figure out what we should do for sure later.
