### ISSUE TITLE
Search Functionality on Search page

### ISSUE THREAD

**Issue by theCyanGiant** [Jypotheren734x/board-game-sharing#93]
Lets make the search form use the exact same format as the library input - Title is the only text input.  Range of players drop down min and max, status either checked in or out, condition range 1(worst)-5(best)  or incomplete.  IF NO TIME AXE ALL SEARCH BUT BY TITLE MVP

**Comment by theCyanGiant** [comment]
inputting drop downs and trying to make them functional. like the inputs I suspect number range will be hazardous.

**Comment by theCyanGiant** [comment]
I have changed to drop downs and styled them but not wired them, they have been committed and pushed.

**Comment by wmwilliams** [comment]
pulled non-"mvp" search extras. if we have time sure, but its thursday.
